apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pgpasswordspc
  namespace: superapp
spec:
  parameters:
    clientID: <identity clientID>
    keyvaultName: <kv name>
    objects: |
      array:
        - |
          objectName: pgpassword
          objectType: secret
    tenantId: <tenant ID>
  provider: azure
  secretObjects:
  - data:
    - key: pgpassword
      objectName: pgpassword
    secretName: pgpassword
    type: Opaque